import time
from app.db.db import get_db

def add_post(user_id, filename, description, base64_image, mime_type):
    """
    Creates a new post with an image.

    @param user_id The ID of the user creating the post.
    @param filename The original filename of the uploaded image.
    @param description The text description of the post.
    @param base64_image The base64-encoded image data.
    @param mime_type The MIME type of the image.
    """
    db = get_db()
    db.execute(
        "INSERT INTO images (user_id, name, description, base64_image, mime_type, uploaded_at) VALUES (?, ?, ?, ?, ?, ?)",
        (user_id, filename, description, base64_image, mime_type, int(time.time()))
    )
    db.commit()

def get_all_posts():
    """
    Retrieves a list of all posts ordered by creation date (descending).

    @return A list of dictionaries representing posts.
    """
    db = get_db()
    post_rows = db.execute("""
        SELECT i.id, i.description, i.uploaded_at, u.username, i.base64_image, i.mime_type 
        FROM images i 
        JOIN users u ON i.user_id = u.id 
        ORDER BY i.uploaded_at DESC
    """).fetchall()
    
    return post_rows

def get_posts_paginated(limit=20, offset=0):
    """
    Retrieves a paginated list of posts.

    @param limit The maximum number of posts to return (default 20).
    @param offset The number of posts to skip (default 0).
    @return A paginated list of post records.
    """
    db = get_db()
    post_rows = db.execute("""
        SELECT i.id, i.description, i.uploaded_at, u.username, i.base64_image, i.mime_type 
        FROM images i 
        JOIN users u ON i.user_id = u.id 
        ORDER BY i.uploaded_at DESC
        LIMIT ? OFFSET ?
    """, (limit, offset)).fetchall()
    
    return post_rows

def get_posts_by_user_paginated(user_id, limit, offset=0):
    """
    Retrieves a paginated list of posts generated by a specific user.

    @param user_id The ID of the user.
    @param limit The maximum number of posts to return.
    @param offset The number of posts to skip.
    @return A paginated list of post records for that user.
    """
    db = get_db()
    post_rows = db.execute("""
        SELECT i.id, i.description, i.uploaded_at, u.username, i.base64_image, i.mime_type
        FROM images i
        JOIN users u ON i.user_id = u.id
        WHERE i.user_id = ?
        GROUP BY i.id
        ORDER BY i.uploaded_at DESC
        LIMIT ? OFFSET ?
    """, (user_id, limit, offset)).fetchall()
    
    return post_rows

def get_post_by_id(post_id,):
    """
    Retrieves a single post by its ID.

    @param post_id The ID of the post.
    @return The post record.
    """
    db = get_db()
    return db.execute("""SELECT i.id, i.base64_image, i.name, i.description, i.user_id, i.mime_type, i.uploaded_at, u.username 
                      FROM images i 
                      JOIN users u ON i.user_id = u.id 
                      WHERE i.id = ?
                      """, (post_id,)).fetchone()

def update_post_image(post_id, image_blob, mime_type):
    """
    Updates the image data and MIME type for an existing post.

    @param post_id The ID of the post to update.
    @param image_blob The new base64-encoded image data.
    @param mime_type The new MIME type.
    """
    db = get_db()
    db.execute("UPDATE images SET base64_image = ?, mime_type = ?, updated_at = ? WHERE id = ?", (image_blob, mime_type, int(time.time()), post_id))
    db.commit()

def update_post_description(post_id, description):
    """
    Updates the description of an existing post.

    @param post_id The ID of the post.
    @param description The new description text.
    """
    db = get_db()
    db.execute("UPDATE images SET description = ?, updated_at = ? WHERE id = ?", (description, int(time.time()), post_id))
    db.commit()

# deletes post if post exists and user id matches
def delete_post(post_id, user_id):
    """
    Deletes a post, provided the post exists and the user has permission to delete it.

    @param post_id The ID of the post.
    @param user_id The ID of the user requesting the deletion.
    @return True if deletion was successful, False otherwise.
    """
    try:
        db = get_db()
        db.execute("DELETE FROM images WHERE id = ? AND user_id = ?", (post_id, user_id))
        db.commit()
        return True
    except Exception as e:
        print(f'[ERROR] Failed to delete post ID: {post_id} for user ID: {user_id}, error: {e}')
        return False